#!/usr/bin/env python3
"""Narration for a film: one WAV per beat with piper, the beat timing the film reads, and the assembled voice track.

    python3 voice.py adhdme-pitch-narration.json

Reads the narration spec (a piper voice, a list of beats with an id, a minimum visual length and a line of text),
synthesises every line to out/voice/<id>.wav, then lays the beats out in order: each beat lasts
max(min, lead + speech + pad). It writes:

    <film>-voice.js   const BEATS = [{id, start, dur, speech}]  the film builds its timeline from this
    out/voice.wav     the narration on one 48 kHz stereo track, each line starting `lead` seconds into its beat

Mix it under the score with ffmpeg (see README). Needs `pip install piper-tts` and a voice from
https://huggingface.co/rhasspy/piper-voices next to the spec.
"""
import json, subprocess, sys, wave
from pathlib import Path
import numpy as np

spec_path = Path(sys.argv[1] if len(sys.argv) > 1 else 'adhdme-pitch-narration.json').resolve()
here = spec_path.parent
spec = json.loads(spec_path.read_text())
stem = spec_path.name.replace('-narration.json', '')
model = here / spec.get('model', 'voices/en_GB-cori-high.onnx')
lead, pad = float(spec.get('lead', .45)), float(spec.get('pad', 1.0))
outdir = here / 'out' / 'voice'
outdir.mkdir(parents=True, exist_ok=True)
SR = 48000

def read_wav(path):
    with wave.open(str(path)) as w:
        sr, n, ch, sw = w.getframerate(), w.getnframes(), w.getnchannels(), w.getsampwidth()
        data = np.frombuffer(w.readframes(n), dtype=np.int16).astype(np.float32) / 32768.0
    if ch > 1: data = data.reshape(-1, ch).mean(axis=1)
    if sr != SR:   # linear resample, fine for speech
        x = np.arange(len(data)) / sr
        xi = np.arange(0, x[-1] if len(x) else 0, 1 / SR)
        data = np.interp(xi, x, data).astype(np.float32)
    return data

beats, t = [], 0.0
for b in spec['beats']:
    text = b.get('text', '').strip()
    speech = 0.0
    if text:
        wav = outdir / f"{b['id']}.wav"
        if spec.get('engine', 'piper') == 'edge':   # Microsoft neural voices (needs `pip install edge-tts` and network access), e.g. en-AU-NatashaNeural
            mp3 = outdir / f"{b['id']}.mp3"
            subprocess.run(['edge-tts', '--voice', spec.get('edge_voice', 'en-AU-NatashaNeural'), '--rate', spec.get('edge_rate', '-5%'), '--text', text, '--write-media', str(mp3)], check=True, capture_output=True)
            subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', str(mp3), '-ac', '1', '-ar', '24000', str(wav)], check=True)
        else:
            subprocess.run(['piper', '--model', str(model), '--output_file', str(wav),
                            '--length_scale', str(spec.get('length_scale', 1.0)), '--sentence_silence', str(spec.get('sentence_silence', .3))],
                           input=text.encode(), check=True, capture_output=True)
        with wave.open(str(wav)) as w: speech = w.getnframes() / w.getframerate()
    dur = max(float(b['min']), (lead + speech + pad) if text else 0.0)
    dur = round(dur * 12) / 12   # cuts on the 1/12 s grid
    beats.append({'id': b['id'], 'start': round(t, 4), 'dur': dur, 'speech': round(speech, 3)})
    t += dur

js = here / f'{stem}-voice.js'
js.write_text('// generated by voice.py from ' + spec_path.name + ': one entry per beat, seconds. The film builds its timeline from this.\n'
              'const BEATS = ' + json.dumps(beats, indent=2) + ';\n')

total = int(round(t * SR))
track = np.zeros(total, dtype=np.float32)
for b in beats:
    if not b['speech']: continue
    data = read_wav(outdir / f"{b['id']}.wav")
    at = int(round((b['start'] + lead) * SR))
    end = min(total, at + len(data))
    track[at:end] += data[:end - at]
peak = float(np.max(np.abs(track))) or 1.0
track = track * min(1.0, 0.89 / peak)
stereo = np.stack([track, track], axis=1)
with wave.open(str(here / 'out' / 'voice.wav'), 'wb') as w:
    w.setnchannels(2); w.setsampwidth(2); w.setframerate(SR)
    w.writeframes((np.clip(stereo, -1, 1) * 32767).astype(np.int16).tobytes())
print(f'{js.name}: {len(beats)} beats, {t:.2f} s total')
for b in beats: print(f"  {b['id']:9s} start {b['start']:7.2f}  dur {b['dur']:5.2f}  speech {b['speech']:5.2f}")
print(f"out/voice.wav: {t:.2f} s at {SR} Hz")
